apiVersion: v1
kind: Service
metadata:
  name: fanfare-backend-test
spec:
  selector:
    app: fanfare-backend-test
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer