apiVersion: v1
kind: Service
metadata:
  name: fanfare-backend-test
spec:
  selector:
    app: fanfare-backend-test
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer